apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-app-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: flask-app-service   # Esse label deve corresponder ao label do Service
  namespaceSelector:
    matchNames:
      - flask-app-dev         # Indica onde procurar os Services
  endpoints:
    - port: metrics           # Deve ser o mesmo nome da porta definido no Service
      path: /metrics
      interval: 10s
