apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
  namespace: flask-backend
data:
  FLASK_ENV: "production"
  LOG_LEVEL: "info"
  PROMETHEUS_METRICS_ENABLED: "true"
  POSTGRES_DB: "flask-db"
  POSTGRES_HOST: "postgres-service.postgres"
  POSTGRES_PORT: "5432"
