apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: flask-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: nicolascf/flask:0.0.0-a9778ee
          ports:
            - containerPort: 5000
          envFrom:
          - secretRef:
              name: flask-secret
          - configMapRef:
              name: flask-config
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolume:
            persistentVolumeReclaimPolicy: Retain # Referenciando o PV diretamente
