apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |
    [server]
    http_port = 3000
    domain = grafana.local
    root_url = %(protocol)s://%(domain)s/
    serve_from_sub_path = true
