apiVersion: v1
kind: Service
metadata:
  name: react-frontend
  namespace: react-frontend
  labels:
    app: react-frontend-service   # Label para identificação
spec:
  selector:
    app: react           # Esse label deve estar nos Pods da sua aplicação
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
      name: metrics          # Nome que será referenciado no ServiceMonitor
  type: NodePort
