apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: flask-app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: nicolascf/flask-app:1.0.0-1ae22fd
          ports:
            - containerPort: 5000
          env:
            - name: ENVIRONMENT
              value: "production"
