apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
spec:
  selector:
    app: ecommerce
  ports:
  - protocol: TCP
    port: 80          # Porta de acesso externa
    targetPort: 5000  # Porta que o Flask está escutando no container
  type: NodePort
